package in.dragonbra.javasteam.protobufs.steam;


// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steam/steammessages_market.steamclient.proto

// Protobuf Java Version: 3.25.2
public final class SteammessagesMarketSteamclient {
  private SteammessagesMarketSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CEconMarket_IsMarketplaceAllowed_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CEconMarket_IsMarketplaceAllowed_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string webcookie = 1;</code>
     * @return Whether the webcookie field is set.
     */
    boolean hasWebcookie();
    /**
     * <code>optional string webcookie = 1;</code>
     * @return The webcookie.
     */
    java.lang.String getWebcookie();
    /**
     * <code>optional string webcookie = 1;</code>
     * @return The bytes for webcookie.
     */
    com.google.protobuf.ByteString
        getWebcookieBytes();
  }
  /**
   * Protobuf type {@code CEconMarket_IsMarketplaceAllowed_Request}
   */
  public static final class CEconMarket_IsMarketplaceAllowed_Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CEconMarket_IsMarketplaceAllowed_Request)
      CEconMarket_IsMarketplaceAllowed_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CEconMarket_IsMarketplaceAllowed_Request.newBuilder() to construct.
    private CEconMarket_IsMarketplaceAllowed_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CEconMarket_IsMarketplaceAllowed_Request() {
      webcookie_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CEconMarket_IsMarketplaceAllowed_Request();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.class, SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.Builder.class);
    }

    private int bitField0_;
    public static final int WEBCOOKIE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object webcookie_ = "";
    /**
     * <code>optional string webcookie = 1;</code>
     * @return Whether the webcookie field is set.
     */
    @java.lang.Override
    public boolean hasWebcookie() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string webcookie = 1;</code>
     * @return The webcookie.
     */
    @java.lang.Override
    public java.lang.String getWebcookie() {
      java.lang.Object ref = webcookie_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          webcookie_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string webcookie = 1;</code>
     * @return The bytes for webcookie.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWebcookieBytes() {
      java.lang.Object ref = webcookie_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        webcookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, webcookie_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, webcookie_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request)) {
        return super.equals(obj);
      }
      SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request other = (SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request) obj;

      if (hasWebcookie() != other.hasWebcookie()) return false;
      if (hasWebcookie()) {
        if (!getWebcookie()
            .equals(other.getWebcookie())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWebcookie()) {
        hash = (37 * hash) + WEBCOOKIE_FIELD_NUMBER;
        hash = (53 * hash) + getWebcookie().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CEconMarket_IsMarketplaceAllowed_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CEconMarket_IsMarketplaceAllowed_Request)
        SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.class, SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.Builder.class);
      }

      // Construct using SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        webcookie_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Request_descriptor;
      }

      @java.lang.Override
      public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request getDefaultInstanceForType() {
        return SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.getDefaultInstance();
      }

      @java.lang.Override
      public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request build() {
        SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request buildPartial() {
        SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request result = new SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.webcookie_ = webcookie_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request) {
          return mergeFrom((SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request other) {
        if (other == SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request.getDefaultInstance()) return this;
        if (other.hasWebcookie()) {
          webcookie_ = other.webcookie_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                webcookie_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object webcookie_ = "";
      /**
       * <code>optional string webcookie = 1;</code>
       * @return Whether the webcookie field is set.
       */
      public boolean hasWebcookie() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string webcookie = 1;</code>
       * @return The webcookie.
       */
      public java.lang.String getWebcookie() {
        java.lang.Object ref = webcookie_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            webcookie_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string webcookie = 1;</code>
       * @return The bytes for webcookie.
       */
      public com.google.protobuf.ByteString
          getWebcookieBytes() {
        java.lang.Object ref = webcookie_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          webcookie_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string webcookie = 1;</code>
       * @param value The webcookie to set.
       * @return This builder for chaining.
       */
      public Builder setWebcookie(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        webcookie_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string webcookie = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebcookie() {
        webcookie_ = getDefaultInstance().getWebcookie();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string webcookie = 1;</code>
       * @param value The bytes for webcookie to set.
       * @return This builder for chaining.
       */
      public Builder setWebcookieBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        webcookie_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CEconMarket_IsMarketplaceAllowed_Request)
    }

    // @@protoc_insertion_point(class_scope:CEconMarket_IsMarketplaceAllowed_Request)
    private static final SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request();
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CEconMarket_IsMarketplaceAllowed_Request>
        PARSER = new com.google.protobuf.AbstractParser<CEconMarket_IsMarketplaceAllowed_Request>() {
      @java.lang.Override
      public CEconMarket_IsMarketplaceAllowed_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CEconMarket_IsMarketplaceAllowed_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CEconMarket_IsMarketplaceAllowed_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CEconMarket_IsMarketplaceAllowed_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CEconMarket_IsMarketplaceAllowed_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool allowed = 1;</code>
     * @return Whether the allowed field is set.
     */
    boolean hasAllowed();
    /**
     * <code>optional bool allowed = 1;</code>
     * @return The allowed.
     */
    boolean getAllowed();

    /**
     * <code>optional uint32 reason = 2;</code>
     * @return Whether the reason field is set.
     */
    boolean hasReason();
    /**
     * <code>optional uint32 reason = 2;</code>
     * @return The reason.
     */
    int getReason();

    /**
     * <code>optional uint32 allowed_at_time = 3;</code>
     * @return Whether the allowedAtTime field is set.
     */
    boolean hasAllowedAtTime();
    /**
     * <code>optional uint32 allowed_at_time = 3;</code>
     * @return The allowedAtTime.
     */
    int getAllowedAtTime();

    /**
     * <code>optional uint32 steamguard_required_days = 4;</code>
     * @return Whether the steamguardRequiredDays field is set.
     */
    boolean hasSteamguardRequiredDays();
    /**
     * <code>optional uint32 steamguard_required_days = 4;</code>
     * @return The steamguardRequiredDays.
     */
    int getSteamguardRequiredDays();

    /**
     * <code>optional bool forms_requested = 7;</code>
     * @return Whether the formsRequested field is set.
     */
    boolean hasFormsRequested();
    /**
     * <code>optional bool forms_requested = 7;</code>
     * @return The formsRequested.
     */
    boolean getFormsRequested();

    /**
     * <code>optional bool forms_require_verification = 8;</code>
     * @return Whether the formsRequireVerification field is set.
     */
    boolean hasFormsRequireVerification();
    /**
     * <code>optional bool forms_require_verification = 8;</code>
     * @return The formsRequireVerification.
     */
    boolean getFormsRequireVerification();

    /**
     * <code>optional uint32 new_device_cooldown_days = 9;</code>
     * @return Whether the newDeviceCooldownDays field is set.
     */
    boolean hasNewDeviceCooldownDays();
    /**
     * <code>optional uint32 new_device_cooldown_days = 9;</code>
     * @return The newDeviceCooldownDays.
     */
    int getNewDeviceCooldownDays();
  }
  /**
   * Protobuf type {@code CEconMarket_IsMarketplaceAllowed_Response}
   */
  public static final class CEconMarket_IsMarketplaceAllowed_Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CEconMarket_IsMarketplaceAllowed_Response)
      CEconMarket_IsMarketplaceAllowed_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CEconMarket_IsMarketplaceAllowed_Response.newBuilder() to construct.
    private CEconMarket_IsMarketplaceAllowed_Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CEconMarket_IsMarketplaceAllowed_Response() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CEconMarket_IsMarketplaceAllowed_Response();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.class, SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.Builder.class);
    }

    private int bitField0_;
    public static final int ALLOWED_FIELD_NUMBER = 1;
    private boolean allowed_ = false;
    /**
     * <code>optional bool allowed = 1;</code>
     * @return Whether the allowed field is set.
     */
    @java.lang.Override
    public boolean hasAllowed() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool allowed = 1;</code>
     * @return The allowed.
     */
    @java.lang.Override
    public boolean getAllowed() {
      return allowed_;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    private int reason_ = 0;
    /**
     * <code>optional uint32 reason = 2;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override
    public boolean hasReason() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public int getReason() {
      return reason_;
    }

    public static final int ALLOWED_AT_TIME_FIELD_NUMBER = 3;
    private int allowedAtTime_ = 0;
    /**
     * <code>optional uint32 allowed_at_time = 3;</code>
     * @return Whether the allowedAtTime field is set.
     */
    @java.lang.Override
    public boolean hasAllowedAtTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 allowed_at_time = 3;</code>
     * @return The allowedAtTime.
     */
    @java.lang.Override
    public int getAllowedAtTime() {
      return allowedAtTime_;
    }

    public static final int STEAMGUARD_REQUIRED_DAYS_FIELD_NUMBER = 4;
    private int steamguardRequiredDays_ = 0;
    /**
     * <code>optional uint32 steamguard_required_days = 4;</code>
     * @return Whether the steamguardRequiredDays field is set.
     */
    @java.lang.Override
    public boolean hasSteamguardRequiredDays() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 steamguard_required_days = 4;</code>
     * @return The steamguardRequiredDays.
     */
    @java.lang.Override
    public int getSteamguardRequiredDays() {
      return steamguardRequiredDays_;
    }

    public static final int FORMS_REQUESTED_FIELD_NUMBER = 7;
    private boolean formsRequested_ = false;
    /**
     * <code>optional bool forms_requested = 7;</code>
     * @return Whether the formsRequested field is set.
     */
    @java.lang.Override
    public boolean hasFormsRequested() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool forms_requested = 7;</code>
     * @return The formsRequested.
     */
    @java.lang.Override
    public boolean getFormsRequested() {
      return formsRequested_;
    }

    public static final int FORMS_REQUIRE_VERIFICATION_FIELD_NUMBER = 8;
    private boolean formsRequireVerification_ = false;
    /**
     * <code>optional bool forms_require_verification = 8;</code>
     * @return Whether the formsRequireVerification field is set.
     */
    @java.lang.Override
    public boolean hasFormsRequireVerification() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool forms_require_verification = 8;</code>
     * @return The formsRequireVerification.
     */
    @java.lang.Override
    public boolean getFormsRequireVerification() {
      return formsRequireVerification_;
    }

    public static final int NEW_DEVICE_COOLDOWN_DAYS_FIELD_NUMBER = 9;
    private int newDeviceCooldownDays_ = 0;
    /**
     * <code>optional uint32 new_device_cooldown_days = 9;</code>
     * @return Whether the newDeviceCooldownDays field is set.
     */
    @java.lang.Override
    public boolean hasNewDeviceCooldownDays() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 new_device_cooldown_days = 9;</code>
     * @return The newDeviceCooldownDays.
     */
    @java.lang.Override
    public int getNewDeviceCooldownDays() {
      return newDeviceCooldownDays_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, allowed_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, reason_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, allowedAtTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, steamguardRequiredDays_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(7, formsRequested_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(8, formsRequireVerification_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt32(9, newDeviceCooldownDays_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, allowed_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, reason_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, allowedAtTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, steamguardRequiredDays_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, formsRequested_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, formsRequireVerification_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, newDeviceCooldownDays_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response)) {
        return super.equals(obj);
      }
      SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response other = (SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response) obj;

      if (hasAllowed() != other.hasAllowed()) return false;
      if (hasAllowed()) {
        if (getAllowed()
            != other.getAllowed()) return false;
      }
      if (hasReason() != other.hasReason()) return false;
      if (hasReason()) {
        if (getReason()
            != other.getReason()) return false;
      }
      if (hasAllowedAtTime() != other.hasAllowedAtTime()) return false;
      if (hasAllowedAtTime()) {
        if (getAllowedAtTime()
            != other.getAllowedAtTime()) return false;
      }
      if (hasSteamguardRequiredDays() != other.hasSteamguardRequiredDays()) return false;
      if (hasSteamguardRequiredDays()) {
        if (getSteamguardRequiredDays()
            != other.getSteamguardRequiredDays()) return false;
      }
      if (hasFormsRequested() != other.hasFormsRequested()) return false;
      if (hasFormsRequested()) {
        if (getFormsRequested()
            != other.getFormsRequested()) return false;
      }
      if (hasFormsRequireVerification() != other.hasFormsRequireVerification()) return false;
      if (hasFormsRequireVerification()) {
        if (getFormsRequireVerification()
            != other.getFormsRequireVerification()) return false;
      }
      if (hasNewDeviceCooldownDays() != other.hasNewDeviceCooldownDays()) return false;
      if (hasNewDeviceCooldownDays()) {
        if (getNewDeviceCooldownDays()
            != other.getNewDeviceCooldownDays()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAllowed()) {
        hash = (37 * hash) + ALLOWED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAllowed());
      }
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason();
      }
      if (hasAllowedAtTime()) {
        hash = (37 * hash) + ALLOWED_AT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getAllowedAtTime();
      }
      if (hasSteamguardRequiredDays()) {
        hash = (37 * hash) + STEAMGUARD_REQUIRED_DAYS_FIELD_NUMBER;
        hash = (53 * hash) + getSteamguardRequiredDays();
      }
      if (hasFormsRequested()) {
        hash = (37 * hash) + FORMS_REQUESTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getFormsRequested());
      }
      if (hasFormsRequireVerification()) {
        hash = (37 * hash) + FORMS_REQUIRE_VERIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getFormsRequireVerification());
      }
      if (hasNewDeviceCooldownDays()) {
        hash = (37 * hash) + NEW_DEVICE_COOLDOWN_DAYS_FIELD_NUMBER;
        hash = (53 * hash) + getNewDeviceCooldownDays();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CEconMarket_IsMarketplaceAllowed_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CEconMarket_IsMarketplaceAllowed_Response)
        SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.class, SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.Builder.class);
      }

      // Construct using SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        allowed_ = false;
        reason_ = 0;
        allowedAtTime_ = 0;
        steamguardRequiredDays_ = 0;
        formsRequested_ = false;
        formsRequireVerification_ = false;
        newDeviceCooldownDays_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesMarketSteamclient.internal_static_CEconMarket_IsMarketplaceAllowed_Response_descriptor;
      }

      @java.lang.Override
      public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response getDefaultInstanceForType() {
        return SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.getDefaultInstance();
      }

      @java.lang.Override
      public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response build() {
        SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response buildPartial() {
        SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response result = new SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.allowed_ = allowed_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reason_ = reason_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.allowedAtTime_ = allowedAtTime_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.steamguardRequiredDays_ = steamguardRequiredDays_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.formsRequested_ = formsRequested_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.formsRequireVerification_ = formsRequireVerification_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.newDeviceCooldownDays_ = newDeviceCooldownDays_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response) {
          return mergeFrom((SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response other) {
        if (other == SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response.getDefaultInstance()) return this;
        if (other.hasAllowed()) {
          setAllowed(other.getAllowed());
        }
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        if (other.hasAllowedAtTime()) {
          setAllowedAtTime(other.getAllowedAtTime());
        }
        if (other.hasSteamguardRequiredDays()) {
          setSteamguardRequiredDays(other.getSteamguardRequiredDays());
        }
        if (other.hasFormsRequested()) {
          setFormsRequested(other.getFormsRequested());
        }
        if (other.hasFormsRequireVerification()) {
          setFormsRequireVerification(other.getFormsRequireVerification());
        }
        if (other.hasNewDeviceCooldownDays()) {
          setNewDeviceCooldownDays(other.getNewDeviceCooldownDays());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                allowed_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                reason_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                allowedAtTime_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                steamguardRequiredDays_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 56: {
                formsRequested_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 56
              case 64: {
                formsRequireVerification_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 64
              case 72: {
                newDeviceCooldownDays_ = input.readUInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean allowed_ ;
      /**
       * <code>optional bool allowed = 1;</code>
       * @return Whether the allowed field is set.
       */
      @java.lang.Override
      public boolean hasAllowed() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool allowed = 1;</code>
       * @return The allowed.
       */
      @java.lang.Override
      public boolean getAllowed() {
        return allowed_;
      }
      /**
       * <code>optional bool allowed = 1;</code>
       * @param value The allowed to set.
       * @return This builder for chaining.
       */
      public Builder setAllowed(boolean value) {

        allowed_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool allowed = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAllowed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        allowed_ = false;
        onChanged();
        return this;
      }

      private int reason_ ;
      /**
       * <code>optional uint32 reason = 2;</code>
       * @return Whether the reason field is set.
       */
      @java.lang.Override
      public boolean hasReason() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 reason = 2;</code>
       * @return The reason.
       */
      @java.lang.Override
      public int getReason() {
        return reason_;
      }
      /**
       * <code>optional uint32 reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(int value) {

        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reason_ = 0;
        onChanged();
        return this;
      }

      private int allowedAtTime_ ;
      /**
       * <code>optional uint32 allowed_at_time = 3;</code>
       * @return Whether the allowedAtTime field is set.
       */
      @java.lang.Override
      public boolean hasAllowedAtTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 allowed_at_time = 3;</code>
       * @return The allowedAtTime.
       */
      @java.lang.Override
      public int getAllowedAtTime() {
        return allowedAtTime_;
      }
      /**
       * <code>optional uint32 allowed_at_time = 3;</code>
       * @param value The allowedAtTime to set.
       * @return This builder for chaining.
       */
      public Builder setAllowedAtTime(int value) {

        allowedAtTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 allowed_at_time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAllowedAtTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        allowedAtTime_ = 0;
        onChanged();
        return this;
      }

      private int steamguardRequiredDays_ ;
      /**
       * <code>optional uint32 steamguard_required_days = 4;</code>
       * @return Whether the steamguardRequiredDays field is set.
       */
      @java.lang.Override
      public boolean hasSteamguardRequiredDays() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 steamguard_required_days = 4;</code>
       * @return The steamguardRequiredDays.
       */
      @java.lang.Override
      public int getSteamguardRequiredDays() {
        return steamguardRequiredDays_;
      }
      /**
       * <code>optional uint32 steamguard_required_days = 4;</code>
       * @param value The steamguardRequiredDays to set.
       * @return This builder for chaining.
       */
      public Builder setSteamguardRequiredDays(int value) {

        steamguardRequiredDays_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 steamguard_required_days = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSteamguardRequiredDays() {
        bitField0_ = (bitField0_ & ~0x00000008);
        steamguardRequiredDays_ = 0;
        onChanged();
        return this;
      }

      private boolean formsRequested_ ;
      /**
       * <code>optional bool forms_requested = 7;</code>
       * @return Whether the formsRequested field is set.
       */
      @java.lang.Override
      public boolean hasFormsRequested() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool forms_requested = 7;</code>
       * @return The formsRequested.
       */
      @java.lang.Override
      public boolean getFormsRequested() {
        return formsRequested_;
      }
      /**
       * <code>optional bool forms_requested = 7;</code>
       * @param value The formsRequested to set.
       * @return This builder for chaining.
       */
      public Builder setFormsRequested(boolean value) {

        formsRequested_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool forms_requested = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormsRequested() {
        bitField0_ = (bitField0_ & ~0x00000010);
        formsRequested_ = false;
        onChanged();
        return this;
      }

      private boolean formsRequireVerification_ ;
      /**
       * <code>optional bool forms_require_verification = 8;</code>
       * @return Whether the formsRequireVerification field is set.
       */
      @java.lang.Override
      public boolean hasFormsRequireVerification() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool forms_require_verification = 8;</code>
       * @return The formsRequireVerification.
       */
      @java.lang.Override
      public boolean getFormsRequireVerification() {
        return formsRequireVerification_;
      }
      /**
       * <code>optional bool forms_require_verification = 8;</code>
       * @param value The formsRequireVerification to set.
       * @return This builder for chaining.
       */
      public Builder setFormsRequireVerification(boolean value) {

        formsRequireVerification_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool forms_require_verification = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormsRequireVerification() {
        bitField0_ = (bitField0_ & ~0x00000020);
        formsRequireVerification_ = false;
        onChanged();
        return this;
      }

      private int newDeviceCooldownDays_ ;
      /**
       * <code>optional uint32 new_device_cooldown_days = 9;</code>
       * @return Whether the newDeviceCooldownDays field is set.
       */
      @java.lang.Override
      public boolean hasNewDeviceCooldownDays() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint32 new_device_cooldown_days = 9;</code>
       * @return The newDeviceCooldownDays.
       */
      @java.lang.Override
      public int getNewDeviceCooldownDays() {
        return newDeviceCooldownDays_;
      }
      /**
       * <code>optional uint32 new_device_cooldown_days = 9;</code>
       * @param value The newDeviceCooldownDays to set.
       * @return This builder for chaining.
       */
      public Builder setNewDeviceCooldownDays(int value) {

        newDeviceCooldownDays_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 new_device_cooldown_days = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewDeviceCooldownDays() {
        bitField0_ = (bitField0_ & ~0x00000040);
        newDeviceCooldownDays_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CEconMarket_IsMarketplaceAllowed_Response)
    }

    // @@protoc_insertion_point(class_scope:CEconMarket_IsMarketplaceAllowed_Response)
    private static final SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response();
    }

    public static SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CEconMarket_IsMarketplaceAllowed_Response>
        PARSER = new com.google.protobuf.AbstractParser<CEconMarket_IsMarketplaceAllowed_Response>() {
      @java.lang.Override
      public CEconMarket_IsMarketplaceAllowed_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CEconMarket_IsMarketplaceAllowed_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CEconMarket_IsMarketplaceAllowed_Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SteammessagesMarketSteamclient.CEconMarket_IsMarketplaceAllowed_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CEconMarket_IsMarketplaceAllowed_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CEconMarket_IsMarketplaceAllowed_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CEconMarket_IsMarketplaceAllowed_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CEconMarket_IsMarketplaceAllowed_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,steam/steammessages_market.steamclient" +
      ".proto\032\036steam/steammessages_base.proto\0322" +
      "steam/steammessages_unified_base.steamcl" +
      "ient.proto\"=\n(CEconMarket_IsMarketplaceA" +
      "llowed_Request\022\021\n\twebcookie\030\001 \001(\t\"\346\001\n)CE" +
      "conMarket_IsMarketplaceAllowed_Response\022" +
      "\017\n\007allowed\030\001 \001(\010\022\016\n\006reason\030\002 \001(\r\022\027\n\017allo" +
      "wed_at_time\030\003 \001(\r\022 \n\030steamguard_required" +
      "_days\030\004 \001(\r\022\027\n\017forms_requested\030\007 \001(\010\022\"\n\032" +
      "forms_require_verification\030\010 \001(\010\022 \n\030new_" +
      "device_cooldown_days\030\t \001(\r2{\n\nEconMarket" +
      "\022m\n\024IsMarketplaceAllowed\022).CEconMarket_I" +
      "sMarketplaceAllowed_Request\032*.CEconMarke" +
      "t_IsMarketplaceAllowed_ResponseB\003\200\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesBase.getDescriptor(),
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        });
    internal_static_CEconMarket_IsMarketplaceAllowed_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CEconMarket_IsMarketplaceAllowed_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CEconMarket_IsMarketplaceAllowed_Request_descriptor,
        new java.lang.String[] { "Webcookie", });
    internal_static_CEconMarket_IsMarketplaceAllowed_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CEconMarket_IsMarketplaceAllowed_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CEconMarket_IsMarketplaceAllowed_Response_descriptor,
        new java.lang.String[] { "Allowed", "Reason", "AllowedAtTime", "SteamguardRequiredDays", "FormsRequested", "FormsRequireVerification", "NewDeviceCooldownDays", });
    SteammessagesBase.getDescriptor();
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
