package in.dragonbra.javasteam.protobufs.csgo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csgo/steammessages_unified_base.steamworkssdk.proto

public final class SteammessagesUnifiedBaseSteamworkssdk {
  private SteammessagesUnifiedBaseSteamworkssdk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.description);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.serviceDescription);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.serviceExecutionSite);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.enumDescription);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.enumValueDescription);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code EProtoExecutionSite}
   */
  public enum EProtoExecutionSite
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EProtoExecutionSiteUnknown = 0;</code>
     */
    k_EProtoExecutionSiteUnknown(0),
    /**
     * <code>k_EProtoExecutionSiteSteamClient = 3;</code>
     */
    k_EProtoExecutionSiteSteamClient(3),
    ;

    /**
     * <code>k_EProtoExecutionSiteUnknown = 0;</code>
     */
    public static final int k_EProtoExecutionSiteUnknown_VALUE = 0;
    /**
     * <code>k_EProtoExecutionSiteSteamClient = 3;</code>
     */
    public static final int k_EProtoExecutionSiteSteamClient_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EProtoExecutionSite valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EProtoExecutionSite forNumber(int value) {
      switch (value) {
        case 0: return k_EProtoExecutionSiteUnknown;
        case 3: return k_EProtoExecutionSiteSteamClient;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EProtoExecutionSite>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EProtoExecutionSite> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EProtoExecutionSite>() {
            public EProtoExecutionSite findValueByNumber(int number) {
              return EProtoExecutionSite.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SteammessagesUnifiedBaseSteamworkssdk.getDescriptor().getEnumTypes().get(0);
    }

    private static final EProtoExecutionSite[] VALUES = values();

    public static EProtoExecutionSite valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EProtoExecutionSite(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EProtoExecutionSite)
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> description = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERVICE_DESCRIPTION_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> serviceDescription = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERVICE_EXECUTION_SITE_FIELD_NUMBER = 50008;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      SteammessagesUnifiedBaseSteamworkssdk.EProtoExecutionSite> serviceExecutionSite = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        SteammessagesUnifiedBaseSteamworkssdk.EProtoExecutionSite.class,
        null);
  public static final int METHOD_DESCRIPTION_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> methodDescription = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ENUM_DESCRIPTION_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.String> enumDescription = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ENUM_VALUE_DESCRIPTION_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> enumValueDescription = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3csgo/steammessages_unified_base.steamw" +
      "orkssdk.proto\032 google/protobuf/descripto" +
      "r.proto*]\n\023EProtoExecutionSite\022 \n\034k_EPro" +
      "toExecutionSiteUnknown\020\000\022$\n k_EProtoExec" +
      "utionSiteSteamClient\020\003:4\n\013description\022\035." +
      "google.protobuf.FieldOptions\030\320\206\003 \001(\t:>\n\023" +
      "service_description\022\037.google.protobuf.Se" +
      "rviceOptions\030\320\206\003 \001(\t:u\n\026service_executio" +
      "n_site\022\037.google.protobuf.ServiceOptions\030" +
      "\330\206\003 \001(\0162\024.EProtoExecutionSite:\034k_EProtoE" +
      "xecutionSiteUnknown:<\n\022method_descriptio" +
      "n\022\036.google.protobuf.MethodOptions\030\320\206\003 \001(" +
      "\t:8\n\020enum_description\022\034.google.protobuf." +
      "EnumOptions\030\320\206\003 \001(\t:C\n\026enum_value_descri" +
      "ption\022!.google.protobuf.EnumValueOptions" +
      "\030\320\206\003 \001(\tB\005H\001\200\001\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    description.internalInit(descriptor.getExtensions().get(0));
    serviceDescription.internalInit(descriptor.getExtensions().get(1));
    serviceExecutionSite.internalInit(descriptor.getExtensions().get(2));
    methodDescription.internalInit(descriptor.getExtensions().get(3));
    enumDescription.internalInit(descriptor.getExtensions().get(4));
    enumValueDescription.internalInit(descriptor.getExtensions().get(5));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
