package in.dragonbra.javasteam.protobufs.steam;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steam/steammessages_remoteclient_service.steamclient.proto

public final class SteammessagesRemoteclientServiceSteamclient {
  private SteammessagesRemoteclientServiceSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:steam/steammessages_remoteclient_servi" +
      "ce.steamclient.proto\0322steam/steammessage" +
      "s_unified_base.steamclient.proto\0327steam/" +
      "steammessages_remoteclient_service_messa" +
      "ges.proto2\354\017\n\014RemoteClient\022\210\001\n\016GetPairin" +
      "gInfo\022%.CRemoteClient_GetPairingInfo_Req" +
      "uest\032&.CRemoteClient_GetPairingInfo_Resp" +
      "onse\"\'\202\265\030#Get pairing info for an entere" +
      "d PIN\022~\n\014NotifyOnline\022\".CRemoteClient_On" +
      "line_Notification\032\013.NoResponse\"=\202\265\0309Let " +
      "the service know we\'re available for sta" +
      "tus listeners\022n\n\021NotifyReplyPacket\022\'.CRe" +
      "moteClient_ReplyPacket_Notification\032\013.No" +
      "Response\"#\202\265\030\037Send a reply to a remote c" +
      "lient\022\237\001\n\022AllocateTURNServer\022).CRemoteCl" +
      "ient_AllocateTURNServer_Request\032*.CRemot" +
      "eClient_AllocateTURNServer_Response\"2\202\265\030" +
      ".Allocate a TURN server for a streaming " +
      "session\022\247\001\n\023AllocateRelayServer\022*.CRemot" +
      "eClient_AllocateRelayServer_Request\032+.CR" +
      "emoteClient_AllocateRelayServer_Response" +
      "\"7\202\265\0303Allocate a UDP relay server for a " +
      "streaming session\022}\n\013AllocateSDR\022\".CRemo" +
      "teClient_AllocateSDR_Request\032#.CRemoteCl" +
      "ient_AllocateSDR_Response\"%\202\265\030!Allocate " +
      "SDR resources for an app\022\203\001\n\030SendSteamBr" +
      "oadcastPacket\022*.CRemoteClient_SteamBroad" +
      "cast_Notification\032\013.NoResponse\".\202\265\030*Broa" +
      "dcast a packet to remote Steam clients\022{" +
      "\n\026SendSteamToSteamPacket\022(.CRemoteClient" +
      "_SteamToSteam_Notification\032\013.NoResponse\"" +
      "*\202\265\030&Send a packet to a remote Steam cli" +
      "ent\022\250\001\n\034SendRemotePlaySessionStarted\022#.C" +
      "RemotePlay_SessionStarted_Request\032$.CRem" +
      "otePlay_SessionStarted_Response\"=\202\265\0309Let" +
      " the server know that we started a Remot" +
      "e Play session\022\224\001\n\034SendRemotePlaySession" +
      "Stopped\022(.CRemotePlay_SessionStopped_Not" +
      "ification\032\013.NoResponse\"=\202\265\0309Let the serv" +
      "er know that we stopped a Remote Play se" +
      "ssion\022\210\001\n\034SendRemotePlayTogetherPacket\022!" +
      ".CRemotePlayTogether_Notification\032\013.NoRe" +
      "sponse\"8\202\265\0304Send a Remote Play Together " +
      "packet to a Steam client\022\311\001\n\"CreateRemot" +
      "ePlayTogetherInvitation\0229.CRemoteClient_" +
      "CreateRemotePlayTogetherInvitation_Reque" +
      "st\032:.CRemoteClient_CreateRemotePlayToget" +
      "herInvitation_Response\",\202\265\030(Create a Rem" +
      "ote Play Together invitation\022\311\001\n\"DeleteR" +
      "emotePlayTogetherInvitation\0229.CRemoteCli" +
      "ent_DeleteRemotePlayTogetherInvitation_R" +
      "equest\032:.CRemoteClient_DeleteRemotePlayT" +
      "ogetherInvitation_Response\",\202\265\030(Delete a" +
      " Remote Play Together invitation\032.\202\265\030*Me" +
      "thods for Steam remote client operations" +
      "2\224\007\n\027RemoteClientSteamClient\022\220\001\n\032NotifyR" +
      "egisterStatusUpdate\0220.CRemoteClient_Regi" +
      "sterStatusUpdate_Notification\032\013.NoRespon" +
      "se\"3\202\265\030/Register for status updates with" +
      " a Steam client\022\226\001\n\034NotifyUnregisterStat" +
      "usUpdate\0222.CRemoteClient_UnregisterStatu" +
      "sUpdate_Notification\032\013.NoResponse\"5\202\265\0301U" +
      "nregister for status updates with a Stea" +
      "m client\022p\n\022NotifyRemotePacket\022(.CRemote" +
      "Client_RemotePacket_Notification\032\013.NoRes" +
      "ponse\"#\202\265\030\037Send a packet to a Steam clie" +
      "nt\022\205\001\n\032NotifySteamBroadcastPacket\022*.CRem" +
      "oteClient_SteamBroadcast_Notification\032\013." +
      "NoResponse\".\202\265\030*Broadcast a packet to re" +
      "mote Steam clients\022\221\001\n\030NotifySteamToStea" +
      "mPacket\022(.CRemoteClient_SteamToSteam_Not" +
      "ification\032\013.NoResponse\">\202\265\030:Send a packe" +
      "t to a Steam client from a remote Steam " +
      "client\022\212\001\n\036NotifyRemotePlayTogetherPacke" +
      "t\022!.CRemotePlayTogether_Notification\032\013.N" +
      "oResponse\"8\202\265\0304Send a Remote Play Togeth" +
      "er packet to a Steam client\0322\202\265\030*Methods" +
      " for Steam remote client operations\300\265\030\002B" +
      "\003\200\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
          SteammessagesRemoteclientServiceMessages.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceExecutionSite);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
    SteammessagesRemoteclientServiceMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
