package in.dragonbra.javasteam.protobufs.csgo;


// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csgo/valveextensions.proto

// Protobuf Java Version: 3.25.2
public final class Valveextensions {
  private Valveextensions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Valveextensions.valveMapField);
    registry.add(Valveextensions.valveMapKey);
    registry.add(Valveextensions.diffEncodeField);
    registry.add(Valveextensions.deltaIgnore);
    registry.add(Valveextensions.steammlMaxEntries);
    registry.add(Valveextensions.steammlIsTimestamp);
    registry.add(Valveextensions.steamlearnCount);
    registry.add(Valveextensions.schemaFriendlyName);
    registry.add(Valveextensions.schemaDescription);
    registry.add(Valveextensions.schemaSuppressEnumerator);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int VALVE_MAP_FIELD_FIELD_NUMBER = 61000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> valveMapField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int VALVE_MAP_KEY_FIELD_NUMBER = 61001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> valveMapKey = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int DIFF_ENCODE_FIELD_FIELD_NUMBER = 61002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> diffEncodeField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int DELTA_IGNORE_FIELD_NUMBER = 61003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> deltaIgnore = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STEAMML_MAX_ENTRIES_FIELD_NUMBER = 61004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> steammlMaxEntries = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int STEAMML_IS_TIMESTAMP_FIELD_NUMBER = 61005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> steammlIsTimestamp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STEAMLEARN_COUNT_FIELD_NUMBER = 61006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> steamlearnCount = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int SCHEMA_FRIENDLY_NAME_FIELD_NUMBER = 1000;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> schemaFriendlyName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SCHEMA_DESCRIPTION_FIELD_NUMBER = 1001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> schemaDescription = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SCHEMA_SUPPRESS_ENUMERATOR_FIELD_NUMBER = 1002;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.Boolean> schemaSuppressEnumerator = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032csgo/valveextensions.proto\032 google/pro" +
      "tobuf/descriptor.proto:?\n\017valve_map_fiel" +
      "d\022\035.google.protobuf.FieldOptions\030\310\334\003 \001(\010" +
      ":\005false:=\n\rvalve_map_key\022\035.google.protob" +
      "uf.FieldOptions\030\311\334\003 \001(\010:\005false:=\n\021diff_e" +
      "ncode_field\022\035.google.protobuf.FieldOptio" +
      "ns\030\312\334\003 \001(\005:\0010:<\n\014delta_ignore\022\035.google.p" +
      "rotobuf.FieldOptions\030\313\334\003 \001(\010:\005false:?\n\023s" +
      "teamml_max_entries\022\035.google.protobuf.Fie" +
      "ldOptions\030\314\334\003 \001(\r:\0010:D\n\024steamml_is_times" +
      "tamp\022\035.google.protobuf.FieldOptions\030\315\334\003 " +
      "\001(\010:\005false:<\n\020steamlearn_count\022\035.google." +
      "protobuf.FieldOptions\030\316\334\003 \001(\r:\0010:@\n\024sche" +
      "ma_friendly_name\022!.google.protobuf.EnumV" +
      "alueOptions\030\350\007 \001(\t:>\n\022schema_description" +
      "\022!.google.protobuf.EnumValueOptions\030\351\007 \001" +
      "(\t:F\n\032schema_suppress_enumerator\022!.googl" +
      "e.protobuf.EnumValueOptions\030\352\007 \001(\010"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    valveMapField.internalInit(descriptor.getExtensions().get(0));
    valveMapKey.internalInit(descriptor.getExtensions().get(1));
    diffEncodeField.internalInit(descriptor.getExtensions().get(2));
    deltaIgnore.internalInit(descriptor.getExtensions().get(3));
    steammlMaxEntries.internalInit(descriptor.getExtensions().get(4));
    steammlIsTimestamp.internalInit(descriptor.getExtensions().get(5));
    steamlearnCount.internalInit(descriptor.getExtensions().get(6));
    schemaFriendlyName.internalInit(descriptor.getExtensions().get(7));
    schemaDescription.internalInit(descriptor.getExtensions().get(8));
    schemaSuppressEnumerator.internalInit(descriptor.getExtensions().get(9));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
